### ISSUE TITLE
Custom boxes support

### ISSUE THREAD

**Issue by hacknug** [marcusforsberg/ACF-Native-Fields#1]
Hey Marcus,

I wanted to ask if you're still planning on adding support for custom boxes. I've just made some changes in a project of mine to move LayGridder's UI inside an ACF tab and I think adding that feature would be great.

Imho, adding support for hooks and all kinds of stuff would be great but maybe we can start just by adding support for Custom boxes where users would input the container's id and a title and that would be it?

**Comment by marcusforsberg** [comment]
Hi @hacknug!

I still intend to add support for custom metaboxes but haven't gotten around to it yet. I'll see what I can do in the coming days.

I'm always open to PRs, too. :)

**Comment by marcusforsberg** [comment]
@hacknug I've now implemented a new option to select "Custom" as the metabox to move, which will then allow you to input your own metabox ID (without the `#`). Feel free to test it and let me know if it works as intended for LayGridder.

**Comment by marcusforsberg** [comment]
https://github.com/marcusforsberg/ACF-Native-Fields/commit/f01c3ee96c284bded663de777a1d8c208198a56b

**Comment by hacknug** [comment]
Works perfectly. Thank you!
